spring:
  profiles.active: dev

---

spring:
  profiles: dev

spring.application:
    name: fezzik
spring.data:
    mongodb:
      host: localhost
      port: 27017
      dbname: fezzik

server:
  port: 8080

management:
  port: 9090
  address: 127.0.0.1

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
    
fezzik:
  rest:
    username: inigo
    passwd: montoya
    role: rest_service

---

spring:
  profiles: docker

spring.application:
    name: fezzik
spring.data:
    mongodb:
      host: mongo
      port: 27017
      dbname: fezzik

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changemeasdf
    key-password: changemeasdf

management:
  port: 9443

endpoints:
  health:
    sensitive: true
  restart:
    enabled: false
  shutdown:
    enabled: false
    
fezzik:
  rest:
    username: inigo
    passwd: montoya
    role: rest_service    
