spring.profiles.active: dev

---

# Use this profile in conjunction with dev or docker
# it will provide basic authentication over 1-way ssl as the security

spring.profiles: basicauth

server:
  port: 8443
  ssl:
    key-store: classpath:tomcat-keystore.jks
    key-store-password: letmeinnow #encrypt
    key-password: letmeinnow #encrypt

management.port: 9443

endpoints:
  health:
    sensitive: true
  restart:
    enabled: false
  shutdown:
    enabled: false
    
fezzik:
  rest:
    username: inigo
    passwd: $2a$16$zZX1uBdeDm.InOGPy3hxp.s3hyyWOo.ObamAQYSySk69FY07aCNv6 # remove this comment later = montoya
    role: rest_service   

---

# Use this profile in conjunction with dev or docker
# it will provide 2-way ssl as the security

spring:
  profiles: pki

server:
  port: 8443
  ssl:
    key-store: classpath:tomcat-keystore.jks
    key-store-password: letmeinnow #encrypt
    key-password: letmeinnow #encrypt
    trust-store: classpath:tomcat-truststore.jks
    trust-store-password: letmeinnow #encrypt
    client-auth: want

management:
  port: 9443

endpoints:
  health:
    sensitive: true
  restart:
    enabled: false
  shutdown:
    enabled: false   

---

spring.profiles: dev
spring.profiles.include: basicauth

spring.application.name: fezzik
    
spring.data:
    mongodb:
      host: localhost
      port: 27017
      dbname: fezzik

---

spring.profiles: docker
spring.profiles.include: pki

spring.application.name: fezzik

spring.data:
    mongodb:
      host: mongo
      port: 27017
      dbname: fezzik
      
server:
  tomcat:
    accesslog:
      directory: /tmp
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'
      suffix: .log          
    

    
     
